/**
 * COMPREHENSIVE DOCUMENT LIBRARY
 * 
 * This library defines ALL document types that can be generated by the BW Nexus AI system.
 * It covers the full spectrum of global economic, governmental, institutional, and commercial needs.
 * 
 * The system is designed to serve:
 * - Governments (national, regional, municipal)
 * - Sovereign Wealth Funds
 * - Development Finance Institutions (DFIs)
 * - Multilateral Organizations (UN, World Bank, IMF, regional banks)
 * - Private Enterprises (Fortune 500 to SMEs)
 * - NGOs and Foundations
 * - Startups and Innovation Labs
 * - Financial Institutions (banks, insurers, funds)
 * - Academic and Research Institutions
 */

// ============================================================================
// DOCUMENT CATEGORY DEFINITIONS
// ============================================================================

export type DocumentCategory = 
  // Foundation Documents
  | 'foundation'
  // Strategic Documents  
  | 'strategic'
  // Legal & Compliance
  | 'legal'
  // Financial & Investment
  | 'financial'
  // Risk & Due Diligence
  | 'risk'
  // Government & Policy
  | 'government'
  // Trade & Commerce
  | 'trade'
  // Partnerships & Alliances
  | 'partnership'
  // Market Intelligence
  | 'intelligence'
  // Operational
  | 'operational'
  // Communications & PR
  | 'communications'
  // Technical & Sector-Specific
  | 'technical'
  // ESG & Sustainability
  | 'esg'
  // Academic & Research
  | 'research';

// ============================================================================
// COMPREHENSIVE DOCUMENT TYPE UNION
// ============================================================================

export type ExtendedDocumentType =
  // === FOUNDATION DOCUMENTS (First Contact, Initial Outreach) ===
  | 'loi'                              // Letter of Intent
  | 'mou'                              // Memorandum of Understanding
  | 'nda'                              // Non-Disclosure Agreement
  | 'term-sheet'                       // Term Sheet
  | 'expression-of-interest'           // EOI
  | 'request-for-information'          // RFI
  | 'request-for-proposal'             // RFP
  | 'request-for-quotation'            // RFQ
  | 'invitation-to-tender'             // ITT
  | 'pre-qualification'                // Pre-Qualification Document
  
  // === STRATEGIC DOCUMENTS ===
  | 'executive-summary'                // 1-2 page overview
  | 'strategic-brief'                  // 3-5 page strategy outline
  | 'strategic-plan'                   // Full 10-20 page plan
  | 'business-case'                    // Investment justification
  | 'feasibility-study'                // Viability assessment
  | 'market-entry-strategy'            // Market expansion plan
  | 'growth-strategy'                  // Scaling roadmap
  | 'exit-strategy'                    // Divestiture/exit plan
  | 'turnaround-plan'                  // Business recovery
  | 'transformation-roadmap'           // Digital/organizational transformation
  | 'vision-document'                  // Long-term aspirational document
  | 'white-paper'                      // Thought leadership
  
  // === LEGAL & COMPLIANCE DOCUMENTS ===
  | 'joint-venture-agreement'          // JV structure
  | 'shareholders-agreement'           // Shareholder rights
  | 'partnership-agreement'            // Partnership terms
  | 'licensing-agreement'              // IP licensing
  | 'franchise-agreement'              // Franchise terms
  | 'distribution-agreement'           // Distribution rights
  | 'supply-agreement'                 // Supply chain contract
  | 'service-agreement'                // Service delivery
  | 'consulting-agreement'             // Advisory services
  | 'employment-agreement'             // Key personnel
  | 'compliance-certificate'           // Regulatory compliance
  | 'regulatory-filing'                // Government submission
  | 'sanctions-clearance'              // Sanctions verification
  | 'anti-corruption-policy'           // FCPA/UK Bribery Act
  | 'data-protection-policy'           // GDPR/privacy
  | 'dispute-resolution'               // Arbitration/mediation
  
  // === FINANCIAL & INVESTMENT DOCUMENTS ===
  | 'financial-model'                  // 5-year projections
  | 'investment-memo'                  // IC memo
  | 'investment-thesis'                // Investment rationale
  | 'capital-raise-deck'               // Fundraising materials
  | 'private-placement-memo'           // PPM
  | 'prospectus'                       // Public offering
  | 'bond-offering'                    // Debt issuance
  | 'project-finance-model'            // Infrastructure financing
  | 'valuation-report'                 // Company/asset valuation
  | 'fairness-opinion'                 // Transaction fairness
  | 'solvency-opinion'                 // Financial health
  | 'credit-analysis'                  // Credit assessment
  | 'cash-flow-analysis'               // Liquidity modeling
  | 'budget-proposal'                  // Budget justification
  | 'cost-benefit-analysis'            // CBA
  | 'roi-analysis'                     // Return analysis
  | 'npv-irr-analysis'                 // Discounted cash flow
  | 'sensitivity-analysis'             // Scenario modeling
  | 'monte-carlo-simulation'           // Probabilistic analysis
  
  // === RISK & DUE DILIGENCE ===
  | 'risk-assessment'                  // Comprehensive risk review
  | 'risk-register'                    // Risk inventory
  | 'risk-mitigation-plan'             // Risk controls
  | 'due-diligence-request'            // Information request
  | 'due-diligence-report'             // DD findings
  | 'legal-due-diligence'              // Legal DD
  | 'financial-due-diligence'          // Financial DD
  | 'commercial-due-diligence'         // Commercial DD
  | 'technical-due-diligence'          // Technical DD
  | 'environmental-due-diligence'      // Environmental DD
  | 'tax-due-diligence'                // Tax DD
  | 'hr-due-diligence'                 // People DD
  | 'it-due-diligence'                 // Technology DD
  | 'background-check'                 // Entity verification
  | 'integrity-due-diligence'          // Corruption/sanctions
  | 'sanctions-screening'              // OFAC/EU/UN screening
  | 'aml-kyc-report'                   // Anti-money laundering
  | 'political-risk-assessment'        // Country/political risk
  | 'country-risk-report'              // Sovereign risk
  | 'currency-risk-analysis'           // FX exposure
  | 'insurance-gap-analysis'           // Coverage assessment
  
  // === GOVERNMENT & POLICY DOCUMENTS ===
  | 'policy-brief'                     // Policy recommendation
  | 'position-paper'                   // Advocacy document
  | 'regulatory-impact-assessment'     // RIA
  | 'legislative-proposal'             // Draft legislation
  | 'cabinet-memo'                     // Government decision memo
  | 'ministerial-briefing'             // Minister brief
  | 'budget-submission'                // Government budget
  | 'public-consultation'              // Citizen engagement
  | 'public-private-partnership'       // PPP proposal
  | 'concession-agreement'             // Infrastructure concession
  | 'sovereign-guarantee'              // Government guarantee
  | 'bilateral-investment-treaty'      // BIT template
  | 'free-trade-agreement'             // FTA analysis
  | 'economic-impact-assessment'       // EIA
  | 'social-impact-assessment'         // SIA
  | 'national-development-plan'        // NDP contribution
  | 'sector-development-strategy'      // Industry policy
  | 'special-economic-zone'            // SEZ proposal
  | 'investment-promotion'             // FDI attraction
  | 'grant-application'                // Funding request
  | 'subsidy-application'              // Incentive request
  
  // === TRADE & COMMERCE ===
  | 'export-plan'                      // Export strategy
  | 'import-analysis'                  // Import sourcing
  | 'trade-finance-proposal'           // Trade financing
  | 'letter-of-credit'                 // LC documentation
  | 'bill-of-lading'                   // Shipping documentation
  | 'customs-declaration'              // Import/export filing
  | 'origin-certificate'               // Certificate of origin
  | 'trade-compliance'                 // Export control
  | 'market-access-analysis'           // Trade barrier analysis
  | 'tariff-analysis'                  // Duty calculation
  | 'supply-chain-mapping'             // Value chain analysis
  | 'procurement-strategy'             // Sourcing plan
  | 'vendor-assessment'                // Supplier evaluation
  
  // === PARTNERSHIP & ALLIANCE ===
  | 'proposal'                         // Partnership proposal
  | 'partnership-assessment'           // Partner evaluation
  | 'partner-comparison'               // Partner comparison matrix
  | 'alliance-framework'               // Strategic alliance
  | 'consortium-agreement'             // Multi-party partnership
  | 'teaming-agreement'                // Joint bid
  | 'co-development-agreement'         // Joint development
  | 'technology-transfer'              // Tech transfer terms
  | 'capacity-building'                // Training program
  | 'local-content-plan'               // Local sourcing
  | 'stakeholder-mapping'              // Stakeholder analysis
  | 'stakeholder-engagement'           // Engagement strategy
  | 'relationship-plan'                // Account management
  | 'partnership-scorecard'            // Partnership health
  
  // === MARKET INTELLIGENCE ===
  | 'dossier'                          // Full market dossier
  | 'market-analysis'                  // Market overview
  | 'industry-analysis'                // Sector deep-dive
  | 'competitive-analysis'             // Competitor landscape
  | 'competitive-intelligence'         // CI report
  | 'swot-analysis'                    // SWOT
  | 'pestle-analysis'                  // PESTLE
  | 'porter-five-forces'               // Industry structure
  | 'value-chain-analysis'             // Value chain
  | 'customer-analysis'                // Buyer behavior
  | 'market-sizing'                    // TAM/SAM/SOM
  | 'trend-analysis'                   // Market trends
  | 'technology-assessment'            // Tech landscape
  | 'innovation-scan'                  // Emerging tech
  | 'business-intelligence-report'     // BI report
  | 'location-analysis'                // Site selection
  | 'labor-market-analysis'            // Workforce assessment
  | 'wage-survey'                      // Compensation study
  | 'real-estate-analysis'             // Property market
  | 'infrastructure-assessment'        // Infra evaluation
  | 'cultural-brief'                   // Cultural intelligence
  | 'entry-advisory'                   // Market entry guide
  
  // === OPERATIONAL DOCUMENTS ===
  | 'operational-plan'                 // Operations roadmap
  | 'implementation-plan'              // Execution timeline
  | 'project-charter'                  // Project authorization
  | 'project-plan'                     // Project management
  | 'milestone-report'                 // Progress tracking
  | 'status-report'                    // Periodic update
  | 'lessons-learned'                  // Post-mortem
  | 'change-management'                // Change program
  | 'integration-plan'                 // M&A integration
  | 'post-merger-integration'          // PMI playbook
  | 'transition-plan'                  // Handover document
  | 'continuity-plan'                  // Business continuity
  | 'disaster-recovery'                // DR plan
  | 'quality-management'               // QMS documentation
  | 'process-documentation'            // SOP
  | 'training-materials'               // Training program
  | 'performance-metrics'              // KPI framework
  | 'dashboard-design'                 // Reporting design
  
  // === COMMUNICATIONS & PR ===
  | 'press-release'                    // Media announcement
  | 'media-kit'                        // Press materials
  | 'investor-presentation'            // Investor deck
  | 'board-presentation'               // Board deck
  | 'annual-report'                    // Yearly report
  | 'quarterly-report'                 // Quarterly update
  | 'shareholder-letter'               // Investor letter
  | 'stakeholder-update'               // Stakeholder comms
  | 'crisis-communication'             // Crisis PR
  | 'internal-memo'                    // Employee comms
  | 'newsletter'                       // Periodic update
  | 'case-study'                       // Success story
  | 'testimonial-collection'           // Client references
  | 'faqs'                             // Q&A document
  | 'talking-points'                   // Speaker brief
  | 'speech-draft'                     // Executive speech
  | 'op-ed'                            // Opinion piece
  
  // === ESG & SUSTAINABILITY ===
  | 'esg-report'                       // ESG disclosure
  | 'sustainability-report'            // Sustainability disclosure
  | 'carbon-footprint'                 // GHG assessment
  | 'net-zero-roadmap'                 // Decarbonization plan
  | 'environmental-impact'             // EIA
  | 'social-impact'                    // SIA
  | 'community-engagement'             // Community plan
  | 'human-rights-assessment'          // HRDD
  | 'labor-standards'                  // Worker conditions
  | 'supply-chain-audit'               // Ethical sourcing
  | 'diversity-inclusion'              // D&I report
  | 'governance-report'                // Corporate governance
  | 'ethics-policy'                    // Code of conduct
  | 'whistleblower-policy'             // Reporting mechanism
  | 'anti-bribery-program'             // ABC program
  | 'green-bond-framework'             // Green financing
  | 'social-bond-framework'            // Social financing
  | 'impact-measurement'               // Impact metrics
  | 'sdg-alignment'                    // UN SDG mapping
  
  // === TECHNICAL & SECTOR-SPECIFIC ===
  | 'technical-specification'          // Technical requirements
  | 'technology-roadmap'               // Tech evolution plan
  | 'patent-analysis'                  // IP landscape
  | 'regulatory-pathway'               // Approval strategy
  | 'clinical-trial-design'            // Healthcare trials
  | 'safety-assessment'                // Product safety
  | 'engineering-study'                // Technical study
  | 'feasibility-engineering'          // Engineering feasibility
  | 'resource-assessment'              // Natural resources
  | 'reserve-report'                   // Mining/oil reserves
  | 'grid-connection'                  // Energy infrastructure
  | 'power-purchase-agreement'         // PPA
  | 'offtake-agreement'                // Commodity offtake
  | 'construction-contract'            // EPC/construction
  | 'maintenance-agreement'            // O&M
  | 'telecom-license'                  // Spectrum/license
  | 'fintech-compliance'               // Financial tech rules
  
  // === RESEARCH & ACADEMIC ===
  | 'research-proposal'                // Academic research
  | 'literature-review'                // Academic review
  | 'methodology'                      // Research method
  | 'data-analysis'                    // Statistical analysis
  | 'findings-report'                  // Research findings
  | 'policy-recommendation'            // Evidence-based policy
  | 'economic-model'                   // Economic modeling
  | 'scenario-analysis'                // Future scenarios
  | 'forecasting-report'               // Projections
  | 'benchmarking-study'               // Comparative analysis
  | 'best-practices'                   // Industry standards
  | 'lessons-from-history'             // Historical analysis
  | 'precedent-analysis'               // Case comparison;

// ============================================================================
// PAGE LENGTH OPTIONS
// ============================================================================

export type PageLength = 1 | 2 | 3 | 4 | 5 | 10 | 15 | 20 | 25 | 30 | 50 | 75 | 100;

export const PAGE_LENGTH_OPTIONS: PageLength[] = [1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 50, 75, 100];

export interface PageLengthPreset {
  value: PageLength;
  label: string;
  description: string;
  useCase: string;
}

export const PAGE_LENGTH_PRESETS: PageLengthPreset[] = [
  { value: 1, label: '1 Page', description: 'Quick summary', useCase: 'Email attachment, quick brief' },
  { value: 2, label: '2 Pages', description: 'Executive brief', useCase: 'Board summary, investor teaser' },
  { value: 3, label: '3 Pages', description: 'Concise report', useCase: 'Decision memo, proposal summary' },
  { value: 5, label: '5 Pages', description: 'Standard brief', useCase: 'Project brief, strategy outline' },
  { value: 10, label: '10 Pages', description: 'Full report', useCase: 'Business case, market analysis' },
  { value: 15, label: '15 Pages', description: 'Detailed report', useCase: 'Due diligence, feasibility study' },
  { value: 20, label: '20 Pages', description: 'Comprehensive', useCase: 'Full dossier, strategic plan' },
  { value: 25, label: '25 Pages', description: 'Extended analysis', useCase: 'Sector study, policy paper' },
  { value: 30, label: '30 Pages', description: 'Full study', useCase: 'Industry report, research paper' },
  { value: 50, label: '50 Pages', description: 'Major report', useCase: 'Annual report, master plan' },
  { value: 75, label: '75 Pages', description: 'Comprehensive study', useCase: 'National strategy, sector master plan' },
  { value: 100, label: '100 Pages', description: 'Full documentation', useCase: 'Complete project documentation' },
];

// ============================================================================
// DOCUMENT TEMPLATE INTERFACE
// ============================================================================

export interface DocumentTemplate {
  id: ExtendedDocumentType;
  title: string;
  description: string;
  category: DocumentCategory;
  defaultPageLength: PageLength;
  minPageLength: PageLength;
  maxPageLength: PageLength;
  timeToGenerate: string;
  requiredInputs: string[];
  optionalInputs: string[];
  outputFormats: ('pdf' | 'docx' | 'html' | 'md' | 'txt')[];
  useCases: string[];
  targetAudience: string[];
  sections: string[];
  aiCapabilities: string[];
}

// ============================================================================
// DOCUMENT TEMPLATES LIBRARY
// ============================================================================

export const EXTENDED_DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  // === FOUNDATION DOCUMENTS ===
  {
    id: 'loi',
    title: 'Letter of Intent',
    description: 'Non-binding expression of partnership interest with key terms and conditions',
    category: 'foundation',
    defaultPageLength: 2,
    minPageLength: 1,
    maxPageLength: 5,
    timeToGenerate: '< 2 min',
    requiredInputs: ['entityName', 'counterparty', 'jurisdiction'],
    optionalInputs: ['dealValue', 'timeline', 'keyTerms'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Initial outreach', 'Preliminary agreement', 'Negotiation start'],
    targetAudience: ['Legal', 'Executive', 'Partner'],
    sections: ['Introduction', 'Intent', 'Key Terms', 'Conditions', 'Signatures'],
    aiCapabilities: ['Precedent matching', 'Legal language optimization', 'Risk flagging'],
  },
  {
    id: 'mou',
    title: 'Memorandum of Understanding',
    description: 'Framework agreement establishing principles before detailed negotiation',
    category: 'foundation',
    defaultPageLength: 5,
    minPageLength: 2,
    maxPageLength: 15,
    timeToGenerate: '< 3 min',
    requiredInputs: ['entityName', 'counterparty', 'scope'],
    optionalInputs: ['governance', 'timeline', 'confidentiality'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Government partnerships', 'Multi-party agreements', 'Research collaborations'],
    targetAudience: ['Legal', 'Government', 'Executive'],
    sections: ['Preamble', 'Definitions', 'Scope', 'Responsibilities', 'Governance', 'Term'],
    aiCapabilities: ['Clause suggestion', 'Precedent analysis', 'Stakeholder mapping'],
  },
  {
    id: 'executive-summary',
    title: 'Executive Summary',
    description: 'High-level strategic overview with key findings and recommendations',
    category: 'strategic',
    defaultPageLength: 2,
    minPageLength: 1,
    maxPageLength: 5,
    timeToGenerate: '< 2 min',
    requiredInputs: ['entityName', 'strategicIntent'],
    optionalInputs: ['market', 'financials', 'risks'],
    outputFormats: ['pdf', 'docx', 'html'],
    useCases: ['Board presentation', 'Investor pitch', 'Decision memo'],
    targetAudience: ['C-Suite', 'Board', 'Investors'],
    sections: ['Overview', 'Opportunity', 'Strategy', 'Financials', 'Risks', 'Recommendation'],
    aiCapabilities: ['Auto-summarization', 'Key insight extraction', 'Visual generation'],
  },
  {
    id: 'dossier',
    title: 'Comprehensive Market Dossier',
    description: 'Complete intelligence package covering market, partners, risks, and strategy',
    category: 'intelligence',
    defaultPageLength: 20,
    minPageLength: 10,
    maxPageLength: 100,
    timeToGenerate: '< 10 min',
    requiredInputs: ['entityName', 'targetMarket', 'strategicIntent'],
    optionalInputs: ['competitors', 'partners', 'financials', 'regulations'],
    outputFormats: ['pdf', 'docx', 'html'],
    useCases: ['Market entry', 'Investment decision', 'Board briefing'],
    targetAudience: ['Executive', 'Board', 'Investment Committee'],
    sections: ['Executive Summary', 'Market Analysis', 'Competitive Landscape', 'Partner Assessment', 'Risk Analysis', 'Financial Projections', 'Implementation Plan', 'Appendices'],
    aiCapabilities: ['Multi-source synthesis', 'Precedent matching', 'Risk scoring', 'RROI calculation', 'SEAM analysis'],
  },
  {
    id: 'risk-assessment',
    title: 'Risk Assessment Report',
    description: 'Comprehensive identification, analysis, and mitigation of all risk categories',
    category: 'risk',
    defaultPageLength: 15,
    minPageLength: 5,
    maxPageLength: 50,
    timeToGenerate: '< 5 min',
    requiredInputs: ['entityName', 'projectScope', 'jurisdiction'],
    optionalInputs: ['financials', 'partners', 'timeline'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Investment approval', 'Board decision', 'Insurance'],
    targetAudience: ['Risk Committee', 'Board', 'Insurers'],
    sections: ['Executive Summary', 'Risk Register', 'Political Risk', 'Market Risk', 'Operational Risk', 'Financial Risk', 'Legal Risk', 'Mitigation Plan', 'Monitoring Framework'],
    aiCapabilities: ['Historical risk analysis', 'Monte Carlo simulation', 'Precedent matching', 'Ethics check'],
  },
  {
    id: 'financial-model',
    title: 'Financial Model & Projections',
    description: '5-year financial projections with scenarios, sensitivities, and valuation',
    category: 'financial',
    defaultPageLength: 10,
    minPageLength: 3,
    maxPageLength: 30,
    timeToGenerate: '< 5 min',
    requiredInputs: ['entityName', 'investmentAmount', 'revenueAssumptions'],
    optionalInputs: ['costStructure', 'capitalStructure', 'exitAssumptions'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Investment decision', 'Fundraising', 'Valuation'],
    targetAudience: ['CFO', 'Investors', 'Board'],
    sections: ['Assumptions', 'Revenue Model', 'Cost Structure', 'Cash Flow', 'P&L', 'Balance Sheet', 'Valuation', 'Sensitivities', 'Scenarios'],
    aiCapabilities: ['SPI calculation', 'IVAS analysis', 'SCF optimization', 'Monte Carlo simulation'],
  },
  {
    id: 'investment-memo',
    title: 'Investment Memorandum',
    description: 'Complete investment justification for committee approval',
    category: 'financial',
    defaultPageLength: 15,
    minPageLength: 5,
    maxPageLength: 50,
    timeToGenerate: '< 8 min',
    requiredInputs: ['entityName', 'investmentAmount', 'targetCompany'],
    optionalInputs: ['valuation', 'dueDiligence', 'terms'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['IC approval', 'Board authorization', 'LP reporting'],
    targetAudience: ['Investment Committee', 'Board', 'LPs'],
    sections: ['Executive Summary', 'Investment Thesis', 'Market Opportunity', 'Company Overview', 'Financials', 'Valuation', 'Risks', 'Terms', 'Recommendation'],
    aiCapabilities: ['Precedent analysis', 'Valuation modeling', 'Risk scoring', 'Comparable deals'],
  },
  {
    id: 'due-diligence-report',
    title: 'Due Diligence Report',
    description: 'Comprehensive findings from legal, financial, and commercial due diligence',
    category: 'risk',
    defaultPageLength: 30,
    minPageLength: 10,
    maxPageLength: 100,
    timeToGenerate: '< 15 min',
    requiredInputs: ['entityName', 'targetCompany', 'ddScope'],
    optionalInputs: ['financials', 'legal', 'commercial', 'technical'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['M&A', 'Investment', 'Partnership'],
    targetAudience: ['Board', 'Legal', 'Investment Team'],
    sections: ['Executive Summary', 'Legal DD', 'Financial DD', 'Commercial DD', 'Technical DD', 'HR DD', 'Tax DD', 'Environmental', 'Red Flags', 'Recommendations'],
    aiCapabilities: ['Document analysis', 'Risk flagging', 'Compliance check', 'Entity verification'],
  },
  {
    id: 'policy-brief',
    title: 'Policy Brief',
    description: 'Evidence-based policy recommendation for government decision-makers',
    category: 'government',
    defaultPageLength: 5,
    minPageLength: 2,
    maxPageLength: 15,
    timeToGenerate: '< 3 min',
    requiredInputs: ['policyTopic', 'jurisdiction', 'recommendation'],
    optionalInputs: ['evidence', 'stakeholders', 'implementation'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Policy advocacy', 'Government briefing', 'Regulatory input'],
    targetAudience: ['Ministers', 'Policy Makers', 'Legislators'],
    sections: ['Issue', 'Background', 'Evidence', 'Options', 'Recommendation', 'Implementation'],
    aiCapabilities: ['Historical precedent', 'Economic impact modeling', 'Stakeholder analysis'],
  },
  {
    id: 'esg-report',
    title: 'ESG Assessment Report',
    description: 'Environmental, Social, and Governance impact assessment and disclosure',
    category: 'esg',
    defaultPageLength: 20,
    minPageLength: 5,
    maxPageLength: 75,
    timeToGenerate: '< 10 min',
    requiredInputs: ['entityName', 'operations', 'geography'],
    optionalInputs: ['emissions', 'workforce', 'governance'],
    outputFormats: ['pdf', 'docx', 'html'],
    useCases: ['Investor disclosure', 'Regulatory compliance', 'Stakeholder reporting'],
    targetAudience: ['Investors', 'Regulators', 'Stakeholders'],
    sections: ['Executive Summary', 'Environmental', 'Social', 'Governance', 'Metrics', 'SDG Alignment', 'Improvement Plan', 'Assurance'],
    aiCapabilities: ['SDG mapping', 'Carbon calculation', 'Benchmark comparison', 'TCFD alignment'],
  },
  {
    id: 'precedent-analysis',
    title: 'Historical Precedent Analysis',
    description: 'Deep analysis of historical cases and patterns relevant to current situation',
    category: 'research',
    defaultPageLength: 15,
    minPageLength: 5,
    maxPageLength: 50,
    timeToGenerate: '< 8 min',
    requiredInputs: ['currentSituation', 'industry', 'geography'],
    optionalInputs: ['timeframe', 'specificPrecedents'],
    outputFormats: ['pdf', 'docx'],
    useCases: ['Strategy development', 'Risk assessment', 'Decision support'],
    targetAudience: ['Strategy', 'Board', 'Advisors'],
    sections: ['Current Context', 'Methodology', 'Historical Cases', 'Pattern Analysis', 'Lessons Learned', 'Application', 'Recommendations'],
    aiCapabilities: ['200-year pattern matching', 'Multi-agent synthesis', 'Scenario projection'],
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getDocumentsByCategory(category: DocumentCategory): DocumentTemplate[] {
  return EXTENDED_DOCUMENT_TEMPLATES.filter(doc => doc.category === category);
}

export function getDocumentById(id: ExtendedDocumentType): DocumentTemplate | undefined {
  return EXTENDED_DOCUMENT_TEMPLATES.find(doc => doc.id === id);
}

export function getAllCategories(): DocumentCategory[] {
  return [...new Set(EXTENDED_DOCUMENT_TEMPLATES.map(doc => doc.category))];
}

export function getDocumentCount(): number {
  return EXTENDED_DOCUMENT_TEMPLATES.length;
}

// Category metadata for UI
export const CATEGORY_METADATA: Record<DocumentCategory, { label: string; description: string; icon: string }> = {
  foundation: { label: 'Foundation', description: 'Initial outreach and preliminary agreements', icon: 'FileText' },
  strategic: { label: 'Strategic', description: 'Strategy, planning, and vision documents', icon: 'Target' },
  legal: { label: 'Legal & Compliance', description: 'Contracts, agreements, and regulatory documents', icon: 'Scale' },
  financial: { label: 'Financial & Investment', description: 'Financial models, valuations, and investment documents', icon: 'DollarSign' },
  risk: { label: 'Risk & Due Diligence', description: 'Risk assessment and due diligence reports', icon: 'AlertCircle' },
  government: { label: 'Government & Policy', description: 'Policy briefs, regulatory filings, and government documents', icon: 'Building2' },
  trade: { label: 'Trade & Commerce', description: 'Trade finance, customs, and supply chain documents', icon: 'Globe' },
  partnership: { label: 'Partnerships', description: 'Partner assessment, alliance frameworks, and collaboration documents', icon: 'Handshake' },
  intelligence: { label: 'Market Intelligence', description: 'Market analysis, competitive intelligence, and research', icon: 'Search' },
  operational: { label: 'Operational', description: 'Implementation plans, project management, and operations', icon: 'Settings' },
  communications: { label: 'Communications', description: 'Press releases, presentations, and stakeholder communications', icon: 'MessageCircle' },
  technical: { label: 'Technical', description: 'Technical specifications and sector-specific documents', icon: 'Cpu' },
  esg: { label: 'ESG & Sustainability', description: 'Environmental, social, and governance reports', icon: 'Leaf' },
  research: { label: 'Research & Academic', description: 'Research papers, analysis, and academic documents', icon: 'BookOpen' },
};

// ============================================================================
// DOCUMENT TYPE COUNT SUMMARY
// ============================================================================

/**
 * TOTAL DOCUMENT TYPES: 200+
 * 
 * Category Breakdown:
 * - Foundation Documents: 10 types
 * - Strategic Documents: 12 types
 * - Legal & Compliance: 16 types
 * - Financial & Investment: 19 types
 * - Risk & Due Diligence: 21 types
 * - Government & Policy: 21 types
 * - Trade & Commerce: 13 types
 * - Partnership & Alliance: 14 types
 * - Market Intelligence: 22 types
 * - Operational: 18 types
 * - Communications & PR: 17 types
 * - ESG & Sustainability: 19 types
 * - Technical & Sector-Specific: 17 types
 * - Research & Academic: 13 types
 * 
 * Page Length Options: 1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 50, 75, 100 pages
 * 
 * Output Formats: PDF, DOCX, HTML, Markdown, Plain Text
 */
