/**
 * COMPREHENSIVE LETTER LIBRARY
 * 
 * This library defines ALL letter types that can be generated by the BW Nexus AI system.
 * Letters are distinct from documents - they are formal communications with specific recipients.
 * 
 * The system supports:
 * - Government-to-Government communications
 * - Business-to-Government (B2G) letters
 * - Business-to-Business (B2B) letters
 * - Investor communications
 * - Regulatory correspondence
 * - Legal notices
 * - Diplomatic communications
 */

// ============================================================================
// LETTER CATEGORY DEFINITIONS
// ============================================================================

export type LetterCategory =
  | 'government-outreach'      // Letters TO government officials
  | 'government-response'      // Letters FROM government (templates)
  | 'investor-relations'       // Investor communications
  | 'partnership-outreach'     // Partner engagement
  | 'legal-notices'            // Legal correspondence
  | 'regulatory'               // Regulatory submissions
  | 'diplomatic'               // International relations
  | 'internal-memos'           // Internal communications
  | 'customer-relations'       // Client communications
  | 'supplier-relations'       // Vendor communications
  | 'banking-finance'          // Financial institution letters
  | 'media-pr'                 // Press and media relations
  | 'employment'               // HR and employment letters
  | 'acknowledgment'           // Confirmations and receipts;

// ============================================================================
// COMPREHENSIVE LETTER TYPE UNION
// ============================================================================

export type ExtendedLetterType =
  // === GOVERNMENT OUTREACH ===
  | 'ministerial-introduction'          // Intro to minister
  | 'investment-promotion-letter'       // FDI inquiry
  | 'incentive-request'                 // Requesting incentives
  | 'regulatory-consultation'           // Seeking regulatory guidance
  | 'permit-application-cover'          // Cover for permit apps
  | 'license-application-cover'         // Cover for license apps
  | 'government-contract-proposal'      // Bidding cover letter
  | 'public-comment-submission'         // Regulatory comments
  | 'policy-advocacy-letter'            // Advocacy letter
  | 'diplomatic-note'                   // Formal diplomatic
  | 'trade-mission-request'             // Trade delegation
  | 'embassy-introduction'              // Embassy outreach
  | 'sovereign-fund-introduction'       // SWF outreach
  | 'dfi-inquiry'                       // Development bank inquiry
  
  // === INVESTOR RELATIONS ===
  | 'investor-update'                   // Regular update
  | 'capital-call-notice'               // Capital call
  | 'distribution-notice'               // Distribution letter
  | 'commitment-confirmation'           // Commitment letter
  | 'investor-onboarding'               // New investor welcome
  | 'fundraising-teaser'                // Initial outreach
  | 'follow-on-opportunity'             // Additional investment
  | 'exit-notification'                 // Exit announcement
  | 'valuation-update'                  // NAV notification
  | 'annual-meeting-invitation'         // AGM invite
  | 'proxy-solicitation'                // Proxy request
  | 'dividend-announcement'             // Dividend notice
  
  // === PARTNERSHIP OUTREACH ===
  | 'partnership-introduction'          // Initial outreach
  | 'partnership-proposal-cover'        // Proposal cover
  | 'joint-venture-invitation'          // JV proposal
  | 'strategic-alliance-proposal'       // Alliance outreach
  | 'collaboration-inquiry'             // Exploring collaboration
  | 'technology-partnership'            // Tech partnership
  | 'distribution-partnership'          // Distribution inquiry
  | 'co-investment-invitation'          // Co-invest opportunity
  | 'merger-interest-letter'            // M&A outreach
  | 'acquisition-interest-letter'       // Acquisition interest
  | 'divestiture-notification'          // Sale announcement
  | 'partnership-termination'           // Ending partnership
  | 'partnership-renewal'               // Renewal proposal
  
  // === LEGAL NOTICES ===
  | 'cease-and-desist'                  // C&D letter
  | 'demand-letter'                     // Payment demand
  | 'breach-notification'               // Contract breach
  | 'termination-notice'                // Contract termination
  | 'dispute-notice'                    // Dispute initiation
  | 'settlement-proposal'               // Settlement offer
  | 'indemnification-claim'             // Indemnity claim
  | 'warranty-claim'                    // Warranty notice
  | 'force-majeure-notice'              // Force majeure claim
  | 'assignment-notice'                 // Contract assignment
  | 'waiver-request'                    // Waiver request
  | 'consent-request'                   // Consent solicitation
  | 'release-letter'                    // Release/discharge
  | 'power-of-attorney'                 // POA letter
  
  // === REGULATORY CORRESPONDENCE ===
  | 'license-renewal-request'           // Renewal application
  | 'compliance-certification'          // Compliance statement
  | 'incident-notification'             // Incident report
  | 'audit-response'                    // Response to audit
  | 'information-request-response'      // RFI response
  | 'exemption-request'                 // Exemption request
  | 'variance-request'                  // Variance application
  | 'appeal-letter'                     // Regulatory appeal
  | 'no-action-request'                 // No-action letter request
  | 'voluntary-disclosure'              // Voluntary disclosure
  | 'whistleblower-response'            // Whistleblower handling
  | 'sanctions-clearance-request'       // Sanctions clearance
  | 'aml-compliance-letter'             // AML attestation
  | 'tax-ruling-request'                // Tax authority request
  
  // === BANKING & FINANCE ===
  | 'credit-facility-request'           // Loan application
  | 'guarantee-request'                 // Bank guarantee
  | 'letter-of-credit-application'      // LC request
  | 'collateral-release-request'        // Collateral release
  | 'refinancing-proposal'              // Refinancing request
  | 'loan-modification-request'         // Loan modification
  | 'covenant-waiver-request'           // Covenant waiver
  | 'payment-extension-request'         // Payment deferral
  | 'account-opening-request'           // New account
  | 'signatory-change-notification'     // Authority change
  | 'wire-transfer-instruction'         // Wire instruction
  | 'escrow-instruction'                // Escrow letter
  | 'comfort-letter-request'            // Comfort letter
  | 'rating-agency-correspondence'      // Rating agency letter
  
  // === MEDIA & PR ===
  | 'press-release-cover'               // PR distribution cover
  | 'media-inquiry-response'            // Responding to press
  | 'interview-confirmation'            // Interview scheduling
  | 'editorial-pitch'                   // Op-ed pitch
  | 'correction-request'                // Media correction
  | 'spokesperson-designation'          // Media contact
  | 'embargo-notification'              // Embargo notice
  | 'crisis-statement'                  // Crisis communication
  | 'event-invitation-media'            // Media event invite
  | 'award-nomination-cover'            // Award submission
  
  // === EMPLOYMENT & HR ===
  | 'offer-letter'                      // Job offer
  | 'employment-verification'           // Employment confirmation
  | 'reference-letter'                  // Reference/recommendation
  | 'promotion-letter'                  // Promotion notice
  | 'transfer-letter'                   // Transfer notification
  | 'warning-letter'                    // Disciplinary warning
  | 'termination-letter'                // Employment termination
  | 'resignation-acceptance'            // Accepting resignation
  | 'non-compete-reminder'              // Non-compete notice
  | 'benefits-enrollment'               // Benefits notification
  | 'salary-revision'                   // Compensation change
  | 'secondment-agreement'              // Secondment letter
  | 'internship-offer'                  // Intern offer
  | 'contractor-engagement'             // Contractor letter
  
  // === CUSTOMER RELATIONS ===
  | 'welcome-letter'                    // New customer
  | 'service-confirmation'              // Service agreement
  | 'delivery-confirmation'             // Delivery notice
  | 'invoice-cover'                     // Invoice transmittal
  | 'payment-receipt'                   // Payment confirmation
  | 'price-change-notification'         // Price adjustment
  | 'service-change-notification'       // Service modification
  | 'complaint-acknowledgment'          // Complaint receipt
  | 'complaint-resolution'              // Resolution letter
  | 'account-closure-confirmation'      // Account closing
  | 'renewal-reminder'                  // Renewal notice
  | 'upsell-proposal'                   // Additional services
  | 'customer-survey-invitation'        // Feedback request
  | 'loyalty-recognition'               // Customer appreciation
  
  // === SUPPLIER RELATIONS ===
  | 'vendor-onboarding'                 // New vendor setup
  | 'purchase-order-cover'              // PO transmittal
  | 'quality-concern'                   // Quality issue
  | 'delivery-delay-inquiry'            // Delay inquiry
  | 'price-negotiation'                 // Price discussion
  | 'contract-renegotiation'            // Terms modification
  | 'vendor-performance-review'         // Performance feedback
  | 'audit-notification'                // Audit notice
  | 'payment-dispute'                   // Payment issue
  | 'supplier-development'              // Improvement request
  | 'exclusivity-request'               // Exclusive agreement
  | 'capacity-inquiry'                  // Capacity check
  | 'emergency-order'                   // Rush order
  | 'vendor-termination'                // Ending relationship
  
  // === ACKNOWLEDGMENTS & CONFIRMATIONS ===
  | 'meeting-confirmation'              // Meeting scheduling
  | 'meeting-minutes-transmittal'       // Minutes distribution
  | 'document-receipt'                  // Document acknowledgment
  | 'instruction-acknowledgment'        // Instruction receipt
  | 'decision-confirmation'             // Decision record
  | 'approval-notification'             // Approval notice
  | 'rejection-notification'            // Rejection notice
  | 'conditional-approval'              // Conditional approval
  | 'closing-confirmation'              // Transaction closing
  | 'transaction-summary'               // Deal summary
  | 'thank-you-letter'                  // Thank you note
  | 'condolence-letter'                 // Sympathy letter
  | 'congratulations-letter'            // Congratulatory note
  
  // === DIPLOMATIC & INTERNATIONAL ===
  | 'embassy-visa-support'              // Visa support letter
  | 'consular-assistance-request'       // Consular help
  | 'bilateral-proposal'                // Bilateral initiative
  | 'multilateral-coordination'         // Multi-country coordination
  | 'trade-delegation-invitation'       // Trade mission invite
  | 'cultural-exchange-proposal'        // Cultural initiative
  | 'humanitarian-cooperation'          // Aid coordination
  | 'treaty-negotiation-proposal'       // Treaty discussion
  | 'economic-cooperation-proposal'     // Economic partnership
  | 'technology-exchange-proposal';     // Tech cooperation

// ============================================================================
// LETTER TEMPLATE INTERFACE
// ============================================================================

export interface LetterTemplate {
  id: ExtendedLetterType;
  title: string;
  description: string;
  category: LetterCategory;
  formality: 'highly-formal' | 'formal' | 'semi-formal' | 'professional';
  requiredFields: string[];
  optionalFields: string[];
  typicalRecipients: string[];
  legalImplications: boolean;
  useCases: string[];
  sections: string[];
  aiCapabilities: string[];
}

// ============================================================================
// LETTER TEMPLATES LIBRARY (Subset for demonstration)
// ============================================================================

export const EXTENDED_LETTER_TEMPLATES: LetterTemplate[] = [
  {
    id: 'ministerial-introduction',
    title: 'Ministerial Introduction Letter',
    description: 'Formal introduction letter to a government minister or senior official',
    category: 'government-outreach',
    formality: 'highly-formal',
    requiredFields: ['entityName', 'ministerName', 'ministry', 'country', 'purpose'],
    optionalFields: ['investmentAmount', 'jobCreation', 'precedentReference'],
    typicalRecipients: ['Minister', 'Permanent Secretary', 'Director General'],
    legalImplications: false,
    useCases: ['FDI introduction', 'Policy advocacy', 'Partnership proposal'],
    sections: ['Salutation', 'Introduction', 'Purpose', 'Value Proposition', 'Request', 'Closing'],
    aiCapabilities: ['Protocol compliance', 'Precedent matching', 'Cultural adaptation'],
  },
  {
    id: 'investment-promotion-letter',
    title: 'Investment Promotion Inquiry',
    description: 'Letter to investment promotion agency requesting information and support',
    category: 'government-outreach',
    formality: 'formal',
    requiredFields: ['entityName', 'targetCountry', 'sector', 'investmentIntent'],
    optionalFields: ['investmentSize', 'timeline', 'incentiveInquiry'],
    typicalRecipients: ['IPA Director', 'Investment Officer', 'Economic Attaché'],
    legalImplications: false,
    useCases: ['Market entry research', 'Incentive inquiry', 'Site selection'],
    sections: ['Introduction', 'Company Background', 'Investment Intent', 'Information Request', 'Next Steps'],
    aiCapabilities: ['Country intelligence', 'Incentive matching', 'Precedent analysis'],
  },
  {
    id: 'partnership-introduction',
    title: 'Partnership Introduction Letter',
    description: 'Initial outreach letter to potential strategic partner',
    category: 'partnership-outreach',
    formality: 'formal',
    requiredFields: ['entityName', 'partnerName', 'partnershipType', 'valueProposition'],
    optionalFields: ['mutualBenefits', 'proposedStructure', 'timeline'],
    typicalRecipients: ['CEO', 'Business Development', 'Strategy Officer'],
    legalImplications: false,
    useCases: ['Strategic alliance', 'JV exploration', 'Distribution partnership'],
    sections: ['Introduction', 'About Us', 'Opportunity', 'Value Proposition', 'Next Steps'],
    aiCapabilities: ['Partner matching', 'SEAM analysis', 'Precedent comparison'],
  },
  {
    id: 'investor-update',
    title: 'Investor Update Letter',
    description: 'Regular update to existing investors on portfolio performance',
    category: 'investor-relations',
    formality: 'professional',
    requiredFields: ['fundName', 'reportingPeriod', 'performance', 'outlook'],
    optionalFields: ['portfolioUpdates', 'exitActivity', 'capitalActivity'],
    typicalRecipients: ['Limited Partners', 'Family Office', 'Institutional Investors'],
    legalImplications: true,
    useCases: ['Quarterly reporting', 'Annual review', 'Material event notification'],
    sections: ['Performance Summary', 'Portfolio Updates', 'Market Commentary', 'Outlook', 'Administrative'],
    aiCapabilities: ['Financial analysis', 'Benchmark comparison', 'Compliance check'],
  },
  {
    id: 'cease-and-desist',
    title: 'Cease and Desist Letter',
    description: 'Formal legal demand to stop specific conduct',
    category: 'legal-notices',
    formality: 'highly-formal',
    requiredFields: ['entityName', 'recipientName', 'violation', 'demandedAction'],
    optionalFields: ['legalBasis', 'deadline', 'consequences'],
    typicalRecipients: ['Individual', 'Company', 'Legal Counsel'],
    legalImplications: true,
    useCases: ['IP infringement', 'Contract violation', 'Unfair competition'],
    sections: ['Identification', 'Factual Background', 'Legal Basis', 'Demand', 'Consequences', 'Response Required'],
    aiCapabilities: ['Legal language optimization', 'Precedent matching', 'Jurisdiction check'],
  },
  {
    id: 'credit-facility-request',
    title: 'Credit Facility Request',
    description: 'Formal request to bank for credit facility or loan',
    category: 'banking-finance',
    formality: 'formal',
    requiredFields: ['entityName', 'bankName', 'facilityType', 'amount', 'purpose'],
    optionalFields: ['collateral', 'terms', 'repaymentPlan'],
    typicalRecipients: ['Relationship Manager', 'Credit Committee', 'Branch Manager'],
    legalImplications: true,
    useCases: ['Working capital', 'Project finance', 'Trade finance', 'Acquisition financing'],
    sections: ['Company Overview', 'Facility Request', 'Purpose', 'Financials', 'Collateral', 'Terms'],
    aiCapabilities: ['Financial analysis', 'Credit assessment', 'Comparable facilities'],
  },
  {
    id: 'compliance-certification',
    title: 'Compliance Certification Letter',
    description: 'Formal certification of regulatory compliance status',
    category: 'regulatory',
    formality: 'highly-formal',
    requiredFields: ['entityName', 'regulatoryBody', 'complianceArea', 'certificationPeriod'],
    optionalFields: ['auditDetails', 'exceptions', 'remediationPlan'],
    typicalRecipients: ['Regulatory Authority', 'Compliance Officer', 'Auditor'],
    legalImplications: true,
    useCases: ['Annual certification', 'License renewal', 'Regulatory examination'],
    sections: ['Identification', 'Certification Statement', 'Scope', 'Compliance Details', 'Signature'],
    aiCapabilities: ['Compliance check', 'Regulatory alignment', 'Exception tracking'],
  },
  {
    id: 'offer-letter',
    title: 'Employment Offer Letter',
    description: 'Formal job offer to prospective employee',
    category: 'employment',
    formality: 'formal',
    requiredFields: ['candidateName', 'position', 'compensation', 'startDate'],
    optionalFields: ['benefits', 'equity', 'signingBonus', 'relocation'],
    typicalRecipients: ['Job Candidate'],
    legalImplications: true,
    useCases: ['New hire', 'Executive recruitment', 'Internal promotion'],
    sections: ['Position', 'Compensation', 'Benefits', 'Start Date', 'Conditions', 'Acceptance'],
    aiCapabilities: ['Compensation benchmarking', 'Legal compliance', 'Benefits optimization'],
  },
];

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

export function getLettersByCategory(category: LetterCategory): LetterTemplate[] {
  return EXTENDED_LETTER_TEMPLATES.filter(letter => letter.category === category);
}

export function getLetterById(id: ExtendedLetterType): LetterTemplate | undefined {
  return EXTENDED_LETTER_TEMPLATES.find(letter => letter.id === id);
}

export function getAllLetterCategories(): LetterCategory[] {
  return [...new Set(EXTENDED_LETTER_TEMPLATES.map(letter => letter.category))];
}

export function getLetterCount(): number {
  // Count all unique letter types from the type union (approximation)
  return 150; // Total letter types defined
}

// Category metadata for UI
export const LETTER_CATEGORY_METADATA: Record<LetterCategory, { label: string; description: string }> = {
  'government-outreach': { label: 'Government Outreach', description: 'Communications to government officials and agencies' },
  'government-response': { label: 'Government Response', description: 'Templates for government reply letters' },
  'investor-relations': { label: 'Investor Relations', description: 'Communications with investors and LPs' },
  'partnership-outreach': { label: 'Partnership Outreach', description: 'Partner engagement and collaboration letters' },
  'legal-notices': { label: 'Legal Notices', description: 'Formal legal correspondence and demands' },
  'regulatory': { label: 'Regulatory', description: 'Regulatory submissions and compliance letters' },
  'diplomatic': { label: 'Diplomatic', description: 'International and diplomatic communications' },
  'internal-memos': { label: 'Internal Memos', description: 'Internal organizational communications' },
  'customer-relations': { label: 'Customer Relations', description: 'Client and customer communications' },
  'supplier-relations': { label: 'Supplier Relations', description: 'Vendor and supplier correspondence' },
  'banking-finance': { label: 'Banking & Finance', description: 'Financial institution communications' },
  'media-pr': { label: 'Media & PR', description: 'Press and public relations communications' },
  'employment': { label: 'Employment', description: 'HR and employment-related letters' },
  'acknowledgment': { label: 'Acknowledgments', description: 'Confirmations and receipt letters' },
};

// ============================================================================
// LETTER TYPE COUNT SUMMARY
// ============================================================================

/**
 * TOTAL LETTER TYPES: 150+
 * 
 * Category Breakdown:
 * - Government Outreach: 14 types
 * - Investor Relations: 12 types
 * - Partnership Outreach: 13 types
 * - Legal Notices: 14 types
 * - Regulatory: 14 types
 * - Banking & Finance: 14 types
 * - Media & PR: 10 types
 * - Employment: 14 types
 * - Customer Relations: 14 types
 * - Supplier Relations: 14 types
 * - Acknowledgments: 13 types
 * - Diplomatic: 10 types
 * 
 * Formality Levels: Highly Formal, Formal, Semi-Formal, Professional
 * 
 * Output Formats: PDF, DOCX
 * 
 * AI Capabilities per Letter:
 * - Precedent matching (historical examples)
 * - Cultural adaptation (regional etiquette)
 * - Legal language optimization
 * - Compliance checking
 * - Stakeholder intelligence
 */
